name: code_coverage_check.
on: [pull_request]


jobs:
  build:
    runs-on: ubuntu-latest


    strategy:
      matrix:
        python-versions: [3.11]


    steps:
      - uses: actions/checkout@v2


      - name: sets_up_python.
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-versions }}
          architecture: x64
          

      - name: install_dependencies.
        run: | 
          pip3.11 install --upgrade pip
          pip install --force-reinstall -vr main_program/requirements.txt
          

      - name: install_coverage.
        run: pip3.11 install coverage


      - name: run_unittests.
        run: |
          coverage run -m unittest discover main_program/source/coding/testing/unit_tests


      - name: report_coverage.
        run: |
          coverage report --fail-under=70 --omit=/usr/*,main_program/source/coding/testing/*
