name: _mutation_testing_validation.
on: [pull_request]


jobs:
  build:
    runs-on: ubuntu-latest


    strategy:
      matrix:
        python-versions: [3.11]


    steps:
      - uses: actions/checkout@v2


      - name: sets_up_python.
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-versions }}
          architecture: x64


      - name: install_dependencies.
        run: | 
          pip3.11 install --upgrade pip
          pip3.11 install --force-reinstall -vr main_program/requirements.txt
          pip3.11 install mutpy


      - name: run_mutation_test.
        run: mut.py --show-mutants --target main_program/source/coding/database/* --unit-test main_program/source/coding/testing/unit_tests/*
